id: P009160
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W6460
  title: དག་སྣང་སྤྲུལ་པའི་གླེགས་བམ
  author: ''
  volumes:
    7aa3016ea52647d58d113f917828de0e:
      image_group_id: I1615
      title: ''
      volume_number: 1
      total_pages: 271
      base_file: v001.txt
