id: I2455B6BB
legacy_id: P009160
ocr_import_info:
  bdrc_scan_id: W6460
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T14:17:39'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:08:53.596631+00:00'
last_modified: 2022-09-04 11:09:03.002474
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W6460
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW6460
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དག་སྣང་སྤྲུལ་པའི་གླེགས་བམ།
  author: ཞབས་དཀར་བ་ཚོགས་དྲུག་རང་གྲོལ།
statistics:
  ocr_word_mean_confidence_index: 0.7551120199653762
  ocr_word_median_confidence_index: 0.8299999833106995
quality: null
bases:
  I1615:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1615
      total_pages: 271
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1615.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7551120199653762
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
