id: I2455B6BB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T14:19:13+00:00'
last_modified: '2022-06-08T09:02:57.261281+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W6460
  title: དག་སྣང་སྤྲུལ་པའི་གླེགས་བམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E6AE:
      image_group_id: I1615
      title: ''
      total_pages: 271
      order: 1
      base_file: E6AE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
